export const mbtiToArchetype: Record<
  string,
  {
    name: string;
    icon: string;
    description: string;
    riskLevel: 'Low' | 'Medium' | 'High';
    noveltyAppetite: 'Low' | 'Medium' | 'High';
    holdingTime: 'Short-term' | 'Mid-term' | 'Long-term';
    tokenPairs: string[];
    strategy: string;
  }
> = {
  ISFP: {
    name: 'The Chill Strategist',
    icon: '🧊',
    description: 'Sensitive but strategic, prefers harmony, makes measured crypto moves.',
    riskLevel: 'Low',
    noveltyAppetite: 'Low',
    holdingTime: 'Mid-term',
    tokenPairs: ['ETH/stETH', 'USDC/DAI'],
    strategy: 'Staking & stable yield farming',
  },
  ISTJ: {
    name: 'The Stable Sergeant',
    icon: '🛡️',
    description: 'Trusts fundamentals, follows routines, serious about safety.',
    riskLevel: 'Low',
    noveltyAppetite: 'Low',
    holdingTime: 'Long-term',
    tokenPairs: ['BTC/ETH', 'WBTC/USDC'],
    strategy: 'Long-term blue-chip holding',
  },
  ENFP: {
    name: 'The Meme Magician',
    icon: '🎭',
    description: 'FOMO-powered, loves the story behind coins, driven by curiosity.',
    riskLevel: 'High',
    noveltyAppetite: 'High',
    holdingTime: 'Short-term',
    tokenPairs: ['DOGE/USDT', 'PEPE/ETH'],
    strategy: 'Meme coin momentum trading',
  },
  INFJ: {
    name: 'The DeFi Deacon',
    icon: '🕊️',
    description: 'Feels the future in protocols, not hype.',
    riskLevel: 'Medium',
    noveltyAppetite: 'Medium',
    holdingTime: 'Mid-term',
    tokenPairs: ['AAVE/ETH', 'LDO/stETH'],
    strategy: 'Protocol governance and staking',
  },
  ESTP: {
    name: 'The Yield Hunter',
    icon: '⛏️',
    description: 'Driven by challenge and reward, goes where the numbers lead.',
    riskLevel: 'High',
    noveltyAppetite: 'High',
    holdingTime: 'Short-term',
    tokenPairs: ['USDT/ETH', 'ARB/GMX'],
    strategy: 'High-yield farms & leverage',
  },
  ISFJ: {
    name: 'The Bitcoin Believer',
    icon: '🟠',
    description: 'Holds the line no matter the storm.',
    riskLevel: 'Low',
    noveltyAppetite: 'Low',
    holdingTime: 'Long-term',
    tokenPairs: ['BTC/ETH'],
    strategy: 'Simple buy & hold',
  },
  ENTP: {
    name: 'The Swing Trader',
    icon: '⚡',
    description: 'Witty and wild, always riding the next chart twist.',
    riskLevel: 'Medium',
    noveltyAppetite: 'High',
    holdingTime: 'Short-term',
    tokenPairs: ['SOL/USDT', 'ETH/BTC'],
    strategy: 'Technical analysis & scalping',
  },
  INTP: {
    name: 'The Privacy Pioneer',
    icon: '🕶️',
    description: 'Stays in the shadows, values sovereignty above all.',
    riskLevel: 'Medium',
    noveltyAppetite: 'Medium',
    holdingTime: 'Mid-term',
    tokenPairs: ['XMR/USDT', 'ZEC/ETH'],
    strategy: 'Privacy coin investments',
  },
  ESTJ: {
    name: 'The Altcoin Cowboy',
    icon: '🤠',
    description: 'Leads meme movements, directs the show, controls the risk.',
    riskLevel: 'High',
    noveltyAppetite: 'Medium',
    holdingTime: 'Short-term',
    tokenPairs: ['SOL/ETH', 'MATIC/USDC'],
    strategy: 'Altcoin swing & narrative trades',
  },
  ENTJ: {
    name: 'The Innovation Investor',
    icon: '🚀',
    description: 'Wants to win the game by redesigning it.',
    riskLevel: 'High',
    noveltyAppetite: 'High',
    holdingTime: 'Mid-term',
    tokenPairs: ['AVAX/USDC', 'OP/ETH'],
    strategy: 'Back high-potential ecosystems early',
  },
  ESFP: {
    name: 'The NFT Enthusiast',
    icon: '🎨',
    description: 'Thinks in JPGs, feels in floor prices.',
    riskLevel: 'High',
    noveltyAppetite: 'High',
    holdingTime: 'Short-term',
    tokenPairs: ['ETH for NFTs'],
    strategy: 'Flipping blue-chip and trending NFTs',
  },
  INFP: {
    name: 'The Gaming Guild Master',
    icon: '🧝‍♀️',
    description: 'Grows digital kingdoms with emotion and imagination.',
    riskLevel: 'Medium',
    noveltyAppetite: 'High',
    holdingTime: 'Mid-term',
    tokenPairs: ['IMX/USDC', 'SAND/MANA'],
    strategy: 'GameFi guild yield + NFT speculation',
  },
  INTJ: {
    name: 'The Airdrop Alchemist',
    icon: '🧪',
    description: 'Plans 5 steps ahead, finds value where others miss it.',
    riskLevel: 'Medium',
    noveltyAppetite: 'Medium',
    holdingTime: 'Mid-term',
    tokenPairs: ['ZK coins', 'testnet tokens'],
    strategy: 'Airdrop farming, protocol exploration',
  },
  INFJ2: {
    name: 'The Risk Oracle',
    icon: '🧿',
    description: 'Guides others, stays calm in multichain chaos.',
    riskLevel: 'Low',
    noveltyAppetite: 'Medium',
    holdingTime: 'Long-term',
    tokenPairs: ['USDC/DAI', 'ETH/wBTC'],
    strategy: 'Cross-chain stable yield',
  },
  ISTP: {
    name: 'The Rebase Ronin',
    icon: '🧬',
    description: 'Finds serenity in passive growth. Cuts losses fast.',
    riskLevel: 'Medium',
    noveltyAppetite: 'Low',
    holdingTime: 'Short-term',
    tokenPairs: ['AMPL/USDC', 'OHM/DAI'],
    strategy: 'Rebase tokens + auto-farming',
  },
  ESFJ: {
    name: 'The Degen Masquerader',
    icon: '🎭',
    description: 'Narrative surfer, quick to adapt, knows what’s hot today.',
    riskLevel: 'High',
    noveltyAppetite: 'High',
    holdingTime: 'Short-term',
    tokenPairs: ['TURBO/PEPE', 'WIF/SOL'],
    strategy: 'Rotational degen betting',
  },
};
